# Generated by Django 5.1.3 on 2024-12-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0002_remove_tarifa_valor_tarifa_valor_te_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribuidora',
            name='codigo',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='valor_te',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='valor_tusd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
