# Generated by Django 5.1.3 on 2025-01-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0003_alter_distribuidora_codigo_alter_tarifa_valor_te_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='dsc_classe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='dsc_detalhe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='dsc_reh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='dsc_subclasse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='dsc_unidade_terciaria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='nom_posto_tarifario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
