# Generated by Django 5.1.3 on 2025-01-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0004_tarifa_dsc_classe_tarifa_dsc_detalhe_tarifa_dsc_reh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='data_geracao_conjunto_dados',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distribuidora',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
