# Generated by Django 5.1.3 on 2024-11-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('instalacao', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('fator_potencia', models.FloatField()),
                ('classificacao_comercial', models.CharField(max_length=50)),
                ('tipo_fornecimento', models.CharField(max_length=50)),
                ('tensao_nominal_disp', models.FloatField()),
                ('limite_min', models.FloatField()),
                ('limite_max', models.FloatField()),
                ('tipo_tarifa', models.CharField(max_length=50)),
            ],
        ),
    ]
