# Generated by Django 5.1.3 on 2024-11-27 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='O CEP deve estar no formato 00000-000.', regex='^\\d{5}-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='classificacao_comercial',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fator_potencia',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_fornecimento',
            field=models.CharField(choices=[('Monofásico', 'Monofásico'), ('Bifásico', 'Bifásico'), ('Trifásico', 'Trifásico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_tarifa',
            field=models.CharField(choices=[('Convencional', 'Convencional'), ('Branca', 'Branca')], max_length=20),
        ),
    ]
