# Generated by Django 5.1.3 on 2024-11-27 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='classificacao_comercial',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial'), ('Rural', 'Rural'), ('Poder Público', 'Poder Público')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='O CNPJ deve estar no formato 00.000.000/0000-00.', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='instalacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='limite_max',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='limite_min',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tensao_nominal_disp',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
