# Generated by Django 5.1.3 on 2025-01-15 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_classificacao_comercial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fator_potencia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='limite_max',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='limite_min',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_tarifa',
        ),
    ]
