# Generated by Django 5.1.3 on 2024-12-13 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaenergia',
            name='consumo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='contaenergia',
            name='demanda',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
