# Generated by Django 5.1.3 on 2024-12-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0002_contaenergia_consumo_contaenergia_demanda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contaenergia',
            name='consumo',
        ),
        migrations.RemoveField(
            model_name='contaenergia',
            name='demanda',
        ),
    ]
