# Generated by Django 5.1.3 on 2024-12-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0003_remove_contaenergia_consumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaenergia',
            name='demanda_contratada',
            field=models.FloatField(default=300.0),
            preserve_default=False,
        ),
    ]
