# Generated by Django 5.1.3 on 2024-12-18 20:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0004_contaenergia_demanda_contratada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('tarifa', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('pis_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('icms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conta_energia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_fatura', to='faturas.contaenergia')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conta_energia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_financeiros', to='faturas.contaenergia')),
            ],
        ),
        migrations.DeleteModel(
            name='ItensFatura',
        ),
    ]
