# Generated by Django 5.1.3 on 2024-12-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0005_itemfatura_itemfinanceiro_delete_itensfatura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemFinanceiro',
        ),
    ]
