# Generated by Django 5.1.3 on 2024-12-26 14:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0006_delete_itemfinanceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('aliquota', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('conta_energia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributos', to='faturas.contaenergia')),
            ],
        ),
    ]
