# Generated by Django 5.1.3 on 2025-01-15 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0007_tributo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contaenergia',
            name='demanda_contratada',
        ),
        migrations.AddField(
            model_name='contaenergia',
            name='demanda_contratada_fora_ponta',
            field=models.FloatField(blank=True, help_text='Preencher apenas para tarifa azul (Alta Tensão).', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='contaenergia',
            name='demanda_contratada_ponta',
            field=models.FloatField(blank=True, help_text='Preencher apenas para tarifa azul (Alta Tensão).', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='contaenergia',
            name='demanda_contratada_unica',
            field=models.FloatField(blank=True, help_text='Preencher apenas para tarifa verde (Alta Tensão).', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='contaenergia',
            name='fator_potencia',
            field=models.FloatField(blank=True, help_text='Fator de potência agora é armazenado aqui em vez do cliente.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='contaenergia',
            name='modalidade',
            field=models.CharField(choices=[('Azul', 'Azul'), ('Azul ABRACE CATIVO', 'Azul ABRACE CATIVO'), ('Azul ABRACE LIVRE', 'Azul ABRACE LIVRE'), ('Verde', 'Verde'), ('Verde ABRACE CATIVO', 'Verde ABRACE CATIVO'), ('Verde ABRACE LIVRE', 'Verde ABRACE LIVRE'), ('Branca', 'Branca'), ('Convencional', 'Convencional'), ('Convencional ABRACE', 'Convencional ABRACE'), ('Convencional pré-pagamento', 'Convencional pré-pagamento')], default='Verde', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contaenergia',
            name='subgrupo',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A3a', 'A3a'), ('A4', 'A4'), ('A4a', 'A4a'), ('A4b', 'A4b'), ('AS', 'AS'), ('B', 'B'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4')], default='Verde', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contaenergia',
            name='leitura_anterior',
            field=models.DateField(help_text='Data da leitura anterior.'),
        ),
        migrations.AlterField(
            model_name='contaenergia',
            name='leitura_atual',
            field=models.DateField(help_text='Data da leitura atual.'),
        ),
        migrations.AlterField(
            model_name='contaenergia',
            name='proxima_leitura',
            field=models.DateField(help_text='Data programada para a próxima leitura.'),
        ),
        migrations.AlterField(
            model_name='contaenergia',
            name='total_pagar',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
