# Generated by Django 5.1.3 on 2025-01-15 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturas', '0008_remove_contaenergia_demanda_contratada_and_more'),
        ('tarifas', '0005_tarifa_data_geracao_conjunto_dados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaenergia',
            name='distribuidora',
            field=models.ForeignKey(default=59, on_delete=django.db.models.deletion.CASCADE, related_name='contas_energia', to='tarifas.distribuidora'),
            preserve_default=False,
        ),
    ]
