# Generated by Django 5.1.3 on 2024-12-13 19:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_cliente_classificacao_comercial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoConsumoDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('demanda_medida_ponta', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('demanda_medida_fora_ponta', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('demanda_medida_reativo_excedente', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('consumo_faturado_ponta_tot', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('consumo_faturado_fora_ponta', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('consumo_faturado_reativo_excedente', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('horario_reservado_consumo', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('horario_reservado_reativo_excedente', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_consumo_demanda', to='clientes.cliente')),
            ],
        ),
    ]
