# Generated by Django 5.1.3 on 2024-12-23 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoconsumodemanda',
            name='mes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
